const MAX_VISIBLE_TOASTS = 3;
const VIEWPORT_OFFSET = "32px";
const TOAST_WIDTH = 360;
const GAP = 14;
const TOAST_LIFETIME = 1000 * 60 * 10;
const TIME_BEFORE_UNMOUNT = 200;

export {
  MAX_VISIBLE_TOASTS,
  VIEWPORT_OFFSET,
  TOAST_WIDTH,
  GAP,
  TOAST_LIFETIME,
  TIME_BEFORE_UNMOUNT,
};
