name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  gh_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4

      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: installing pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Building library
        run: pnpm install --no-frozen-lockfile && pnpm run build

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
